Repository SOPT-all/35-APPJAM-SERVER-BBANGZIP, pull requests merged in 2025-01, with the labels that each got.

#6 [feat] #5 Redis 의존성 추가
  build.gradle
Labels: 영주🐣

#10 :sparkles: [feat] #7 Token 관련 클래스 구현
  src/main/java/com/sopt/bbangzip/domain/token/entity/Token.java
  src/main/java/com/sopt/bbangzip/domain/token/repository/TokenRepository.java
Labels: 영주🐣, feat⚡

#20 :recycle: [fix] #19 화이트리스트에 헬스체크 경로 추가
  src/main/java/com/sopt/bbangzip/common/constants/AuthConstant.java
Labels: 영주🐣, fix🔧

#25 :sparkles: [feat] #17 소셜 로그인 API 구현 완료
  build.gradle
  src/main/java/com/sopt/bbangzip/common/constants/AuthConstant.java
  src/main/java/com/sopt/bbangzip/common/constants/KakaoConstant.java
  src/main/java/com/sopt/bbangzip/common/exception/code/ErrorCode.java
  src/main/java/com/sopt/bbangzip/domain/auth/AuthController.java
  src/main/java/com/sopt/bbangzip/domain/auth/AuthService.java
  src/main/java/com/sopt/bbangzip/domain/token/api/JwtTokensDto.java
  src/main/java/com/sopt/bbangzip/domain/token/service/TokenRemover.java
  src/main/java/com/sopt/bbangzip/domain/token/service/TokenRetriever.java
  src/main/java/com/sopt/bbangzip/domain/token/service/TokenSaver.java
  src/main/java/com/sopt/bbangzip/domain/user/entity/User.java
  src/main/java/com/sopt/bbangzip/domain/user/repository/UserRepository.java
  src/main/java/com/sopt/bbangzip/domain/user/service/UserRetriever.java
  src/main/java/com/sopt/bbangzip/fegin/config/FeignConfig.java
  src/main/java/com/sopt/bbangzip/fegin/kakao/client/KakaoAuthClient.java
  src/main/java/com/sopt/bbangzip/fegin/kakao/client/KakaoInfoClient.java
  src/main/java/com/sopt/bbangzip/fegin/kakao/client/KakaoLogoutClient.java
  src/main/java/com/sopt/bbangzip/fegin/kakao/client/KakaoReissueClient.java
  src/main/java/com/sopt/bbangzip/fegin/kakao/client/KakaoUnlinkClient.java
  src/main/java/com/sopt/bbangzip/fegin/kakao/dto/KakaoLogoutResponse.java
  src/main/java/com/sopt/bbangzip/fegin/kakao/dto/KakaoReissueRequest.java
  src/main/java/com/sopt/bbangzip/fegin/kakao/dto/KakaoTokenResponse.java
  src/main/java/com/sopt/bbangzip/fegin/kakao/dto/KakaoUnlinkResponse.java
  src/main/java/com/sopt/bbangzip/fegin/kakao/dto/KakaoUserInfoResponse.java
  src/main/java/com/sopt/bbangzip/fegin/kakao/service/KakaoService.java
  src/main/java/com/sopt/bbangzip/security/jwt/JwtTokenProvider.java
  src/main/java/com/sopt/bbangzip/test/TestController.java
Labels: 영주🐣, feat⚡

#32 :sparkles: [feat] #26 리프레시 토큰으로 엑세스 토큰 재발급 로직 구현
  src/main/java/com/sopt/bbangzip/common/exception/code/ErrorCode.java
  src/main/java/com/sopt/bbangzip/domain/auth/AuthController.java
  src/main/java/com/sopt/bbangzip/domain/auth/AuthService.java
  src/main/java/com/sopt/bbangzip/domain/token/api/ReissueJwtTokensDto.java
  src/main/java/com/sopt/bbangzip/domain/token/service/TokenRemover.java
  src/main/java/com/sopt/bbangzip/domain/token/service/TokenRetriever.java
  src/main/java/com/sopt/bbangzip/security/jwt/JwtTokenProvider.java
Labels: 영주🐣, feat⚡

#35 :sparkles: [feat] #33 로그아웃 API 구현
  src/main/java/com/sopt/bbangzip/common/exception/code/ErrorCode.java
  src/main/java/com/sopt/bbangzip/domain/auth/AuthController.java
  src/main/java/com/sopt/bbangzip/domain/auth/AuthService.java
  src/main/java/com/sopt/bbangzip/domain/token/repository/TokenRepository.java
  src/main/java/com/sopt/bbangzip/domain/token/service/TokenRemover.java
  src/main/java/com/sopt/bbangzip/domain/token/service/TokenRetriever.java
Labels: 영주🐣, feat⚡

#37 :sparkles: [feat] #36 회원탈퇴 API 구현
  src/main/java/com/sopt/bbangzip/domain/auth/AuthController.java
  src/main/java/com/sopt/bbangzip/domain/auth/AuthService.java
  src/main/java/com/sopt/bbangzip/domain/user/service/UserRemover.java
Labels: 영주🐣, feat⚡

#50 :sparkles: [feat] #44 공부 조각 완료 체크 API 구현
  src/main/java/com/sopt/bbangzip/common/constants/entity/UserTableConstants.java
  src/main/java/com/sopt/bbangzip/common/exception/code/ErrorCode.java
  src/main/java/com/sopt/bbangzip/domain/badge/Badge.java
  src/main/java/com/sopt/bbangzip/domain/badge/BadgeCondition.java
  src/main/java/com/sopt/bbangzip/domain/badge/BadgeResponse.java
  src/main/java/com/sopt/bbangzip/domain/badge/BadgeService.java
  src/main/java/com/sopt/bbangzip/domain/badge/MassBakingBreadBadge.java
  src/main/java/com/sopt/bbangzip/domain/badge/StartBakingBreadBadge.java
  src/main/java/com/sopt/bbangzip/domain/badge/TodayBreadSoldOutBadge.java
  src/main/java/com/sopt/bbangzip/domain/piece/api/controller/PieceController.java
  src/main/java/com/sopt/bbangzip/domain/piece/api/dto/request/IsFinishedDto.java
  src/main/java/com/sopt/bbangzip/domain/piece/api/dto/response/MarkDoneResponse.java
  src/main/java/com/sopt/bbangzip/domain/piece/entity/Piece.java
  src/main/java/com/sopt/bbangzip/domain/piece/repository/PieceRepository.java
  src/main/java/com/sopt/bbangzip/domain/piece/service/PieceRetriever.java
  src/main/java/com/sopt/bbangzip/domain/piece/service/PieceService.java
  src/main/java/com/sopt/bbangzip/domain/piece/service/PieceUpdater.java
  src/main/java/com/sopt/bbangzip/domain/user/entity/User.java
  src/main/java/com/sopt/bbangzip/domain/user/service/UserRetriever.java
  src/main/java/com/sopt/bbangzip/domain/userSubject/entity/UserSubject.java
Labels: 영주🐣, feat⚡

#54 :sparkles: [feat] #51 공부 조각 미완료 체크 API 구현
  src/main/java/com/sopt/bbangzip/domain/piece/api/controller/PieceController.java
  src/main/java/com/sopt/bbangzip/domain/piece/service/PieceService.java
  src/main/java/com/sopt/bbangzip/domain/piece/service/PieceUpdater.java
Labels: 영주🐣, feat⚡

#60 ✨ [feat] #59 얻은 뱃지 조회 API 구현
  src/main/java/com/sopt/bbangzip/domain/badge/Badge.java
  src/main/java/com/sopt/bbangzip/domain/badge/BadgeCondition.java
  src/main/java/com/sopt/bbangzip/domain/badge/MassBakingBreadBadge.java
  src/main/java/com/sopt/bbangzip/domain/badge/StartBakingBreadBadge.java
  src/main/java/com/sopt/bbangzip/domain/badge/TodayBreadSoldOutBadge.java
  src/main/java/com/sopt/bbangzip/domain/badge/api/controller/BadgeController.java
  src/main/java/com/sopt/bbangzip/domain/badge/api/dto/response/BadgeListResponse.java
  src/main/java/com/sopt/bbangzip/domain/badge/api/dto/response/BadgeResponse.java
  src/main/java/com/sopt/bbangzip/domain/badge/service/BadgeService.java
  src/main/java/com/sopt/bbangzip/domain/piece/api/dto/response/MarkDoneResponse.java
  src/main/java/com/sopt/bbangzip/domain/piece/service/PieceService.java
  src/main/java/com/sopt/bbangzip/domain/piece/service/PieceUpdater.java
  src/main/java/com/sopt/bbangzip/domain/user/api/controller/UserController.java
Labels: 예은🐇, feat⚡

#62 [feat] #42 오늘 할 일/밀린 공부 view + 정렬 API 구현 완료
  src/main/java/com/sopt/bbangzip/domain/badge/BadgeRetriever.java
  src/main/java/com/sopt/bbangzip/domain/piece/api/controller/PieceController.java
  src/main/java/com/sopt/bbangzip/domain/piece/api/dto/request/PieceDeleteRequestDto.java
  src/main/java/com/sopt/bbangzip/domain/piece/api/dto/response/TodoPiecesResponse.java
  src/main/java/com/sopt/bbangzip/domain/piece/repository/PieceRepository.java
  src/main/java/com/sopt/bbangzip/domain/piece/service/PieceRetriever.java
  src/main/java/com/sopt/bbangzip/domain/piece/service/PieceService.java
Labels: 영주🐣, feat⚡

#65 :sparkles: [feat] #63 뱃지 획득함과 동시에 레벨 업뎃하는 로직 추가
  src/main/java/com/sopt/bbangzip/domain/badge/service/BadgeService.java
Labels: 영주🐣, fix🔧

#69 :sparkles: [feat] #66 오늘 할 공부 감추기 API
  src/main/java/com/sopt/bbangzip/domain/piece/api/controller/PieceController.java
  src/main/java/com/sopt/bbangzip/domain/piece/entity/Piece.java
  src/main/java/com/sopt/bbangzip/domain/piece/service/PieceService.java
Labels: 영주🐣, feat⚡

#70 ✏️ [fix] #68 공부 조각 삭제하기 API 수정
  src/main/java/com/sopt/bbangzip/domain/piece/api/dto/request/PieceDeleteRequestDto.java
  src/main/java/com/sopt/bbangzip/domain/piece/service/PieceRemover.java
  src/main/java/com/sopt/bbangzip/domain/piece/service/PieceService.java
Labels: 예은🐇, fix🔧

#77 ✏️ [fix] #76 필드명 오타 수정
  src/main/java/com/sopt/bbangzip/domain/badge/api/dto/response/BadgeResponse.java
Labels: 영주🐣, fix🔧

#83 :sparkles: [feat] #82 오늘 할 공부 추가하기 API 에서 유저 정보 관련 로직 수정
  src/main/java/com/sopt/bbangzip/domain/piece/repository/PieceRepository.java
  src/main/java/com/sopt/bbangzip/domain/piece/service/PieceRetriever.java
  src/main/java/com/sopt/bbangzip/domain/piece/service/PieceService.java
Labels: 영주🐣, fix🔧

#85 :sparkles: [feat] #84 공부 조각 삭제하기 API 에서 유저 정보에 해당하는 조각 찾아오도록 수정
  src/main/java/com/sopt/bbangzip/domain/piece/api/controller/PieceController.java
  src/main/java/com/sopt/bbangzip/domain/piece/service/PieceRetriever.java
  src/main/java/com/sopt/bbangzip/domain/piece/service/PieceService.java
Labels: 영주🐣, fix🔧

#89 ✏️ [fix] #88 마이페이지에서 레벨 별 최대 포인트 추가
  src/main/java/com/sopt/bbangzip/domain/badge/service/BadgeService.java
  src/main/java/com/sopt/bbangzip/domain/user/api/dto/UserLevelResponseDto.java
  src/main/java/com/sopt/bbangzip/domain/user/service/UserLevelCalculator.java
  src/main/java/com/sopt/bbangzip/domain/user/service/UserService.java
Labels: 예은🐇, fix🔧

#92 :sparkles: [feat] #91 소셜 로그인 API 에서 code 대신 accessToken 사용해서 구현하도록 수정
  src/main/java/com/sopt/bbangzip/domain/auth/AuthService.java
Labels: 영주🐣, fix🔧

#100 ✏️ [fix] #98 유저 정보 추가
  src/main/java/com/sopt/bbangzip/domain/piece/repository/PieceRepository.java
  src/main/java/com/sopt/bbangzip/domain/piece/service/PieceRetriever.java
  src/main/java/com/sopt/bbangzip/domain/study/service/StudyService.java
  src/main/java/com/sopt/bbangzip/domain/subject/api/controller/SubjectController.java
  src/main/java/com/sopt/bbangzip/domain/subject/api/dto/response/SubjectResponseDto.java
  src/main/java/com/sopt/bbangzip/domain/subject/repository/SubjectRepository.java
  src/main/java/com/sopt/bbangzip/domain/subject/service/SubjectRetriever.java
  src/main/java/com/sopt/bbangzip/domain/subject/service/SubjectService.java
  src/main/java/com/sopt/bbangzip/domain/userSubject/entity/UserSubject.java
Labels: 예은🐇, fix🔧

#108 :clown_face: [chore] #107 더미 이미지 추가
  src/main/java/com/sopt/bbangzip/domain/badge/entity/MassBakingBreadBadge.java
  src/main/java/com/sopt/bbangzip/domain/badge/entity/PreparingOpenBakery.java
  src/main/java/com/sopt/bbangzip/domain/badge/entity/StartBakingBreadBadge.java
  src/main/java/com/sopt/bbangzip/domain/badge/entity/TodayBreadSoldOutBadge.java
  src/main/java/com/sopt/bbangzip/domain/user/service/UserService.java
Labels: 영주🐣, chore

#111 :recycle: [fix] #110 뱃지 획득 관련 로직 오류 수정
  src/main/java/com/sopt/bbangzip/common/advice/ResponseDtoAdvice.java
  src/main/java/com/sopt/bbangzip/domain/badge/service/BadgeService.java
  src/main/java/com/sopt/bbangzip/domain/piece/service/PieceUpdater.java
  src/main/java/com/sopt/bbangzip/domain/user/entity/User.java
Labels: 영주🐣, fix🔧

#113 :recycle: [fix] #112 실패 응답 형식 수정
  src/main/java/com/sopt/bbangzip/common/advice/ResponseDtoAdvice.java
Labels: 영주🐣, fix🔧

#116 :recycle: [fix] #114 PieceService 에서 잘못된 옵션에 대한 예외 처리 수정
  src/main/java/com/sopt/bbangzip/domain/piece/service/PieceService.java
Labels: 영주🐣, fix🔧

#120 ✏️ [fix] #117 반환 응답값 수정
  src/main/java/com/sopt/bbangzip/domain/piece/api/dto/response/MarkDoneResponse.java
  src/main/java/com/sopt/bbangzip/domain/piece/service/PieceService.java
Labels: 영주🐣, fix🔧

#125 :recycle: [fix] #124 CascadeType.REMOVE 추가
  src/main/java/com/sopt/bbangzip/domain/study/entity/Study.java
Labels: 영주🐣, fix🔧

#127 ✏️ [fix] #109 레벨 이름 및 레벨 별 설명 추가
  src/main/java/com/sopt/bbangzip/domain/user/service/UserService.java
Labels: 예은🐇, fix🔧

#131 :sparkles: [feat] #126 뱃지 목 데이터 구현
  src/main/java/com/sopt/bbangzip/common/constants/entity/UserTableConstants.java
  src/main/java/com/sopt/bbangzip/domain/badge/api/controller/BadgeController.java
  src/main/java/com/sopt/bbangzip/domain/badge/entity/escapebadge/EscapeBadge1.java
  src/main/java/com/sopt/bbangzip/domain/badge/entity/escapebadge/EscapeBadgeAapjam.java
  src/main/java/com/sopt/bbangzip/domain/badge/entity/escapebadge/MassBakingBreadBadge.java
  src/main/java/com/sopt/bbangzip/domain/badge/entity/escapebaerlybadge/EscapeBarelyBadge1.java
  src/main/java/com/sopt/bbangzip/domain/badge/entity/escapebaerlybadge/EscapeBarelyBadge2.java
  src/main/java/com/sopt/bbangzip/domain/badge/entity/escapebaerlybadge/EscapeBarelyBadge3.java
  src/main/java/com/sopt/bbangzip/domain/badge/entity/inssabossbadge/InssaBossBadge1.java
  src/main/java/com/sopt/bbangzip/domain/badge/entity/inssabossbadge/InssaBossBadge2.java
  src/main/java/com/sopt/bbangzip/domain/badge/entity/startbadge/PreparingOpenBakery.java
  src/main/java/com/sopt/bbangzip/domain/badge/entity/startbadge/StartBakingBreadBadge.java
  src/main/java/com/sopt/bbangzip/domain/badge/entity/startbadge/TodayBreadSoldOutBadge.java
  src/main/java/com/sopt/bbangzip/domain/badge/service/BadgeService.java
  src/main/java/com/sopt/bbangzip/domain/user/entity/User.java
Labels: 영주🐣, feat⚡

#135 ✏️ [fix] #134 유저 레벨 1로 설정한 부분 Builder에서 제거
  src/main/java/com/sopt/bbangzip/domain/exam/api/dto/response/ExamResponseDto.java
  src/main/java/com/sopt/bbangzip/domain/user/entity/User.java
Labels: 예은🐇, fix🔧

#137 ✏️ [fix] #130 레벨 이미지 추가
  src/main/java/com/sopt/bbangzip/domain/user/service/UserService.java
Labels: 예은🐇, fix🔧

#138 ✏️ [fix] 서비스단 모든 파라미터에 final 추가
  src/main/java/com/sopt/bbangzip/domain/badge/service/BadgeService.java
  src/main/java/com/sopt/bbangzip/domain/exam/service/ExamRetriever.java
  src/main/java/com/sopt/bbangzip/domain/exam/service/ExamSaver.java
  src/main/java/com/sopt/bbangzip/domain/exam/service/ExamService.java
  src/main/java/com/sopt/bbangzip/domain/piece/service/PieceRemover.java
  src/main/java/com/sopt/bbangzip/domain/piece/service/PieceRetriever.java
  src/main/java/com/sopt/bbangzip/domain/piece/service/PieceSaver.java
  src/main/java/com/sopt/bbangzip/domain/piece/service/PieceUpdater.java
  src/main/java/com/sopt/bbangzip/domain/study/service/StudyRetriever.java
  src/main/java/com/sopt/bbangzip/domain/study/service/StudySaver.java
  src/main/java/com/sopt/bbangzip/domain/study/service/StudyService.java
  src/main/java/com/sopt/bbangzip/domain/subject/service/SubjectRemover.java
  src/main/java/com/sopt/bbangzip/domain/subject/service/SubjectRetriever.java
  src/main/java/com/sopt/bbangzip/domain/subject/service/SubjectService.java
  src/main/java/com/sopt/bbangzip/domain/subject/service/SubjectUpdater.java
  src/main/java/com/sopt/bbangzip/domain/user/service/UserService.java
  src/main/java/com/sopt/bbangzip/domain/userSubject/repository/UserSubjectRepository.java
  src/main/java/com/sopt/bbangzip/domain/userSubject/service/UserSubjectRetriever.java
  src/main/java/com/sopt/bbangzip/domain/userSubject/service/UserSubjectSaver.java
  src/main/java/com/sopt/bbangzip/domain/userSubject/service/UserSubjectService.java
Labels: 영주🐣, fix🔧

#141 :recycle: [fix] #139 시험 지난 공부 조각들은 오늘 할 일 view 에서 보이지 않도록 수정
  src/main/java/com/sopt/bbangzip/domain/piece/api/controller/PieceController.java
  src/main/java/com/sopt/bbangzip/domain/piece/repository/PieceRepository.java
Labels: 영주🐣, fix🔧

#142 ✏️ [fix] #140 과목추가 API에서 중복 과목 등록 불가
  src/main/java/com/sopt/bbangzip/domain/subject/repository/SubjectRepository.java
  src/main/java/com/sopt/bbangzip/domain/subject/service/SubjectService.java
  src/main/java/com/sopt/bbangzip/domain/subject/service/SubjectUpdater.java
Labels: 예은🐇, fix🔧

#147 ✏️ [fix] #146 과목 삭제를 위한 Exam 엔티티 수정
  src/main/java/com/sopt/bbangzip/domain/exam/entity/Exam.java
Labels: 예은🐇, fix🔧

#151 ✏️ [fix] #149 교재 추가 API 수정
  src/main/java/com/sopt/bbangzip/domain/exam/repository/ExamRepository.java
  src/main/java/com/sopt/bbangzip/domain/exam/service/ExamRetriever.java
  src/main/java/com/sopt/bbangzip/domain/study/service/StudyService.java
Labels: 예은🐇, fix🔧

#157 :recycle: [fix] #156 얻은 뱃지 조회 API 에서 닉네임도 함께 반환
  src/main/java/com/sopt/bbangzip/domain/badge/api/dto/response/BadgeListResponse.java
  src/main/java/com/sopt/bbangzip/domain/badge/service/BadgeService.java
Labels: 영주🐣, fix🔧

#155 ✏️ [fix] #153 Exam d-day 반환 수정
  src/main/java/com/sopt/bbangzip/domain/subject/service/SubjectService.java
Labels: 예은🐇, fix🔧

#161 ✏️ [fix] #159 과목 명 수정 시 동일 과목명으로 수정 불가
  src/main/java/com/sopt/bbangzip/domain/subject/repository/SubjectRepository.java
  src/main/java/com/sopt/bbangzip/domain/subject/service/SubjectRetriever.java
  src/main/java/com/sopt/bbangzip/domain/subject/service/SubjectService.java
Labels: 예은🐇, fix🔧

#166 :sparkles: [feat] #165 필수 파라미터 누락 에러 핸들링 추가
  src/main/java/com/sopt/bbangzip/common/advice/GlobalExceptionHandler.java
Labels: 영주🐣, feat⚡

#168 ✏️ [fix] #167 남은 공부, 밀린 공부 개수 반환 로직 수정
  src/main/java/com/sopt/bbangzip/domain/piece/repository/PieceRepository.java
Labels: 예은🐇, fix🔧

#172 :sparkles: [chore] 더미 뱃지 조건 수정
  src/main/java/com/sopt/bbangzip/domain/badge/entity/escapebadge/EscapeBadge1.java
  src/main/java/com/sopt/bbangzip/domain/badge/entity/escapebadge/EscapeBadgeAapjam.java
  src/main/java/com/sopt/bbangzip/domain/badge/entity/escapebaerlybadge/EscapeBarelyBadge1.java
  src/main/java/com/sopt/bbangzip/domain/badge/entity/escapebaerlybadge/EscapeBarelyBadge2.java
  src/main/java/com/sopt/bbangzip/domain/badge/entity/escapebaerlybadge/EscapeBarelyBadge3.java
  src/main/java/com/sopt/bbangzip/domain/badge/entity/inssabossbadge/InssaBossBadge1.java
  src/main/java/com/sopt/bbangzip/domain/badge/entity/inssabossbadge/InssaBossBadge2.java
Labels: 영주🐣, chore
